---
- name: Provision headnode
  hosts: login_server
  become: true
  vars_files:
    - ./vars/main.yml
  roles:
    - role: kuutti
      kuutti_provision: head

- name: Provision computenodes
  hosts: compute_servers
  become: true
  vars_files:
    - ./vars/main.yml
  roles:
    - role: kuutti
      kuutti_provision: compute
...
