---
- name: Add OpenHPC repo
  ansible.builtin.dnf:
    name: "{{ kuutti_openhpc_repository_url }}"
    disable_gpg_check: true
    state: present

- name: Install DNF-Plugin-Core and EPEL-Release
  ansible.builtin.dnf:
    name:
      - epel-release
      - dnf-plugins-core
    state: present

- name: Enable powertools repository
  ansible.builtin.command: dnf config-manager --set-enabled powertools
  changed_when: false
