---
# Slurm properties
kuutti_cluster_name: kuutti
kuutti_partition_name: batch
kuutti_max_task_time: "24:00:00"

kuutti_enable_omni_path_support: false
kuutti_default_env: gnu12-mvapich2
kuutti_configure_spack: true
kuutti_enable_intel: false
kuutti_dev_tools:
  - ohpc-autotools
  - hwloc-ohpc
  - valgrind-ohpc
  - cmake-ohpc
  - libtool-ohpc
  - spack-ohpc
  - EasyBuild-ohpc
  - test-suite-ohpc
kuutti_ohpc_packages:
  - gnu12-compilers-ohpc
  - mvapich2-psm2-gnu12-ohpc
  - ohpc-gnu12-mvapich2-parallel-libs
  - ohpc-gnu12-serial-libs
  - ohpc-gnu12-io-libs
  - ohpc-gnu12-python-libs
  - ohpc-gnu12-runtimes
# Installed on all nodes
kuutti_common_packages:
  - python3.11
  - python3.11-devel
  - vim
  - neovim

kuutti_openhpc_repository_url: http://repos.openhpc.community/OpenHPC/3/EL_9/x86_64/ohpc-release-3-1.el9.x86_64.rpm 

kuutti_cluster_network_cidr: 10.0.0.0/24
